version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: lib_management_db
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
